name: backend-dev
recipe: wordpress
config:
  php: '8.0'
  via: nginx
  database: mysql:8.0

tooling:
  build:
    description: Manually invokes all our build steps
    cmd:
      - appserver: sh /app/.kotw/build.sh
